/**
 * HydraDB native schema — maps Foundry entity types to typed Cypher labels and properties.
 */

export const NODE_SCHEMAS = {
  BuildRun: {
    label: 'BuildRun',
    idPrefix: 'build_',
    requiredProps: ['id', 'status'],
    indexedProps: ['status', 'passed', 'started_at'],
  },
  BuildAttempt: {
    label: 'BuildAttempt',
    idPrefix: 'attempt_',
    requiredProps: ['id', 'attempt_number', 'status'],
    indexedProps: ['attempt_number', 'status', 'build_ok', 'preview_ok'],
  },
  Failure: {
    label: 'Failure',
    idPrefix: 'fail_',
    requiredProps: ['id', 'failure_class'],
    indexedProps: ['failure_class'],
  },
  FailureClass: {
    label: 'FailureClass',
    idPrefix: '',
    requiredProps: ['id', 'name'],
    indexedProps: ['name'],
  },
  Strategy: {
    label: 'Strategy',
    idPrefix: 'strategy_',
    requiredProps: ['id', 'name'],
    indexedProps: ['name'],
  },
  StrategyVersion: {
    label: 'StrategyVersion',
    idPrefix: 'strategyv_',
    requiredProps: ['id', 'version', 'status'],
    indexedProps: ['status', 'version'],
  },
  Standard: {
    label: 'Standard',
    idPrefix: 'std_',
    requiredProps: ['id', 'name'],
    indexedProps: ['name'],
  },
  StandardVersion: {
    label: 'StandardVersion',
    idPrefix: 'stdv_',
    requiredProps: ['id', 'version', 'status'],
    indexedProps: ['status', 'version'],
  },
  Capability: {
    label: 'Capability',
    idPrefix: 'cap_',
    requiredProps: ['id', 'name'],
    indexedProps: ['name'],
  },
  Product: {
    label: 'Product',
    idPrefix: 'prod_',
    requiredProps: ['id', 'name'],
    indexedProps: ['name'],
  },
  Site: {
    label: 'Site',
    idPrefix: 'site_',
    requiredProps: ['id', 'name'],
    indexedProps: ['name', 'url'],
  },
  Deployment: {
    label: 'Deployment',
    idPrefix: 'deploy_',
    requiredProps: ['id', 'status'],
    indexedProps: ['status'],
  },
  Artifact: {
    label: 'Artifact',
    idPrefix: 'art_',
    requiredProps: ['id', 'sha256'],
    indexedProps: ['sha256'],
  },
  Idea: {
    label: 'Idea',
    idPrefix: 'idea_',
    requiredProps: ['id', 'name'],
    indexedProps: ['name'],
  },
  IdeaGenerator: {
    label: 'IdeaGenerator',
    idPrefix: 'gen_',
    requiredProps: ['id', 'name'],
    indexedProps: ['name'],
  },
  ResearchReport: {
    label: 'ResearchReport',
    idPrefix: 'res_',
    requiredProps: ['id', 'title'],
    indexedProps: [],
  },
  Observation: {
    label: 'Observation',
    idPrefix: 'obs_',
    requiredProps: ['id', 'metric', 'status'],
    indexedProps: ['metric', 'status'],
  },
  Hypothesis: {
    label: 'Hypothesis',
    idPrefix: 'hyp_',
    requiredProps: ['id', 'statement', 'status'],
    indexedProps: ['status'],
  },
  Experiment: {
    label: 'Experiment',
    idPrefix: 'exp_',
    requiredProps: ['id', 'name'],
    indexedProps: ['name'],
  },
  ExperimentArm: {
    label: 'ExperimentArm',
    idPrefix: 'arm_',
    requiredProps: ['id', 'name'],
    indexedProps: [],
  },
  Model: {
    label: 'Model',
    idPrefix: 'model_',
    requiredProps: ['id', 'name'],
    indexedProps: ['name', 'family'],
  },
  ModelVersion: {
    label: 'ModelVersion',
    idPrefix: 'modelv_',
    requiredProps: ['id', 'model_id', 'version'],
    indexedProps: ['model_id'],
  },
  ModelConfiguration: {
    label: 'ModelConfiguration',
    idPrefix: 'mc_',
    requiredProps: ['id', 'model_version_id'],
    indexedProps: [],
  },
  Component: {
    label: 'Component',
    idPrefix: 'comp_',
    requiredProps: ['id', 'name'],
    indexedProps: ['name'],
  },
  ComponentVersion: {
    label: 'ComponentVersion',
    idPrefix: 'compv_',
    requiredProps: ['id', 'component_id', 'version'],
    indexedProps: ['component_id'],
  },
  Procedure: {
    label: 'Procedure',
    idPrefix: 'proc_',
    requiredProps: ['id', 'name'],
    indexedProps: ['name'],
  },
  ProcedureVersion: {
    label: 'ProcedureVersion',
    idPrefix: 'procv_',
    requiredProps: ['id', 'procedure_id', 'version', 'status'],
    indexedProps: ['status'],
  },
  Lesson: {
    label: 'Lesson',
    idPrefix: 'lesson_',
    requiredProps: ['id', 'statement'],
    indexedProps: [],
  },
};

export const RELATIONSHIP_TYPES = {
  GENERATED: 'GENERATED',
  PROPOSES: 'PROPOSES',
  RESEARCHED_BY: 'RESEARCHED_BY',
  BUILT_FROM: 'BUILT_FROM',
  BUILT_BY: 'BUILT_BY',
  PRODUCED: 'PRODUCED',
  HAS_ATTEMPT: 'HAS_ATTEMPT',
  EXECUTED_TASK: 'EXECUTED_TASK',
  FAILED_WITH: 'FAILED_WITH',
  INSTANCE_OF: 'INSTANCE_OF',
  FIXED_BY: 'FIXED_BY',
  VERIFIED_BY: 'VERIFIED_BY',
  CREATED_ARTIFACT: 'CREATED_ARTIFACT',
  IMPLEMENTS: 'IMPLEMENTS',
  EXPOSES: 'EXPOSES',
  DEPLOYED_AS: 'DEPLOYED_AS',
  DEPENDS_ON: 'DEPENDS_ON',
  CONFORMS_TO: 'CONFORMS_TO',
  AFFECTS: 'AFFECTS',
  SUPERSEDES: 'SUPERSEDES',
  USED_STRATEGY: 'USED_STRATEGY',
  HAS_VERSION: 'HAS_VERSION',
  USED_MODEL: 'USED_MODEL',
  OBSERVED_BY: 'OBSERVED_BY',
  MEASURES: 'MEASURES',
  TESTS: 'TESTS',
  HAS_ARM: 'HAS_ARM',
  ASSIGNED_TO: 'ASSIGNED_TO',
  SUPPORTS: 'SUPPORTS',
  CONTRADICTS: 'CONTRADICTS',
  DERIVED_FROM: 'DERIVED_FROM',
  SUPPORTED_BY: 'SUPPORTED_BY',
  INPUT_TO: 'INPUT_TO',
  OUTPUT_OF: 'OUTPUT_OF',
  BELONGS_TO_PROJECT: 'BELONGS_TO_PROJECT',
  FROM_REPOSITORY: 'FROM_REPOSITORY',
  AT_COMMIT: 'AT_COMMIT',
  USED_COMPONENT: 'USED_COMPONENT',
  IMPLEMENTED_BY: 'IMPLEMENTED_BY',
  HAS_PROCEDURE: 'HAS_PROCEDURE',
  LEARNS_FROM: 'LEARNS_FROM',
};
